### ISSUE TITLE
Assigning a light_ptr instance to itself?

### ISSUE THREAD

**Issue by ziriax** [SodiumFRP/heist-cxx#2]
It seems that the light_ptr assignment operator first decreases its count and then increases the count of the other incoming instance. But what happens when the developer assigns a light_ptr instance to itself? Shouldn't the other count  be incremented first, to prevent an access violation or memory corruption?

**Comment by the-real-blackh** [comment]
This doesn't happen in the code where it's used so there's no bug at present. But you're right. This is wrong, so I've fixed it.
